require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'investorV2' do
  config = use_native_modules!

  $RNFirebaseAnalyticsWithoutAdIdSupport=true
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true

  permissions_path = '../node_modules/react-native-permissions/ios'
     pod 'Permission-Camera', :path => "#{permissions_path}/Camera/Permission-Camera.podspec"
     pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary/Permission-PhotoLibrary.podspec"
     pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"
     pod 'GoogleSignIn'

  post_install do |installer|
     react_native_post_install(installer)
     __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    #  installer.pods_project.targets.each do |target|
    #      target.build_configurations.each do |config|
    #         config.build_settings['OTHER_CPLUSPLUSFLAGS'] = ''
    #         config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    #         # config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
    #      end
    #  end

     installer.pods_project.targets.each do |target|
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            end
        end
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
  
        case target.name
        when 'RCT-Folly'
          target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
          end
        end
      end
  end
end

target 'ImageNotification' do
#   pod 'Firebase/Messaging', '~> 10.0.0'
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true
end
