const Languages = {
    board: {
        title1: 'Đầu tư an toàn cùng TienNgay.vn',
        txt1: 'TienNgay.vn có giấy phép kinh doanh và hoạt động theo quy định của pháp luật và đồng nhất trên toàn hệ thống. Số tiền lãi được trả đúng hạn theo cam kết, giải quyết thắc mắc (nếu có) tận tình, nhanh chóng.',
        title2: 'Lãi suất hấp dẫn cùng TienNgay.vn ',
        txt2: 'Tham gia gửi tiền có kỳ hạn Online tại TienNgay.vn để có thêm thời gian tận hưởng cuộc sống và luôn an tâm rằng tiền của bạn đang sinh lời với lãi suất hấp dẫn.',
        title3: 'Rõ ràng - Minh bạch',
        txt3: 'Tất cả các thao tác của Nhà đầu tư được ghi lại bằng hệ thống của TienNgay.vn, đảm bảo số tiền lãi nhận về rõ ràng, minh bạch.'
    },
    transaction: {
        title: 'Lịch sử giao dịch',
        debtNow: 'Số dư hiện có',
        all: 'Tất cả',
        inMoney: 'Tiền vào',
        outMoney: 'Tiền ra',
        transaction: 'Giao dịch',
        fromDate: 'Từ ngày',
        toDate: 'Tới ngày',
        allInvestNow: 'Tổng đầu tư hiện tại',
        noDataTransaction: 'Bạn chưa thực hiện giao dịch nào!'
    },
    home: {
        title: 'Trang chủ',
        sumInvest: 'Tổng vốn đầu tư',
        sumpProfit: 'Tiền lãi đã nhận',
        sumResidualProfit: 'Tiền lãi còn lại',
        totalCaption: 'Tiền vốn còn lại',
        balanceVimo: 'Số dư ví Vimo',
        rootReceived: 'Tiền vốn đã nhận',
        have: 'Đang có',
        vnd: ' VNĐ',
        invest: 'Đầu tư',
        report: 'Báo cáo',
        payment: 'Thanh toán',
        investPackages: 'Các gói đầu tư nổi bật',
        investNow: 'Đầu tư ngay',
        more: 'Xem thêm',
        stockVfs: 'Chứng khoán VPS',
        question: 'Câu hỏi thường gặp',
        titleLuckyLott: 'Vé số Vietlott trực tuyến',
        describeLuckyLott: 'Thuận tiện, nhanh chóng, an toàn',
        signFree: 'Đăng ký mở tài khoản miễn phí',
        todoInvest: 'Làm thế nào để đầu tư vào TienNgay.vn?',
        todoWithDrawMoney: 'Làm thế nào để rút tiền từ TienNgay.vn?',
        percentCalculated: 'Phần trăm lãi đầu tư được tính như thế nào?',
        paymentMethod: 'Hình thức trả tiền như thế nào?',
        interestRateMonth: 'Lãi xuất tháng',
        timeInvest: 'Thời gian đầu tư',
        interestExpected: 'Lãi dự kiến',
        formInterestPay: 'Hình thức trả lãi',
        hello: 'Chào mừng bạn đến với',
        nameApp: 'TienNgay.Vn',
        investAndAccumulate: 'Đầu tư & Tích luỹ',
        newMedia: 'Tin tức truyền thông',
        investNowFloral: 'ĐẦU TƯ NGAY',
        noNotify: 'Bạn không có thông báo nào',
        reasonInvest: 'Vì sao bạn nên đầu tư vào TienNgay.vn?',
        reasonOne: '1. Đầu tư dễ dàng chỉ từ 3 triệu đồng.',
        reasonTwo: '2. Lợi nhuận cạnh tranh: lãi suất tiền gửi lên đến 18%/năm.',
        reasonThree: '3. Linh hoạt thời hạn, vòng đầu tư ngắn 1 tháng - 24 tháng.',
        reasonFour: '4. Tài sản của bạn được quản lý minh bạch và bảo vệ bởi công ty thuộc tập đoàn công nghệ hàng đầu NextTech.',
        reasonFive: '5. Quản lý dòng tiền thông minh với ứng dụng công nghệ.'
    },
    invest: {
        title: 'Đầu tư',
        investing: 'Đang đầu tư',
        history: 'Đã đáo hạn',
        enter: 'Nhập số tiền mà bạn muốn tìm kiếm',
        time: 'Thời gian đầu tư',
        remaining: 'Tổng gốc còn lại',
        payed: 'Tổng gốc đã nhận',
        dateInvest: 'Ngày đầu tư',
        dueDate: 'Ngày đáo hạn',
        dueDateETA: 'Ngày đáo hạn dự kiến',
        formalPayment: 'Hình thức trả lãi',
        investNow: 'Đầu tư ngay',
        interest: 'Lãi suất tháng',
        interestYear: 'Lãi suất năm',
        attractInvest: 'Đầu tư hấp dẫn',
        intent: 'Tổng lãi dự kiến',
        getMoney: 'Tổng lãi đã nhận',
        sumMoney: 'Tổng gốc đã nhận',
        monthInvest: 'Thời gian đầu tư',
        chooseMoney: 'Số tiền đầu tư',
        packageInvest: 'Tìm kiếm gói đầu tư',
        search: 'Tìm kiếm',
        cancel: 'Hủy',
        notify: 'Thông báo',
        notifyPromotion: 'Thông tin khuyến mại',
        notifyAll: 'Tất cả',
        notifyUnRead: 'Chưa đọc',
        customerGratitude: 'Tri ân khách hàng cùng tienngay.vn',
        investPay: 'Trả lãi đầu tư',
        investSuccess: 'Đầu tư thành công',
        changePercent: 'Thay đổi tích luỹ phần trăm',
        availableBalance: 'Số dư hiện có',
        policy: 'Điều khoản sử dụng và chính sách',
        updateBankInfo:
            'Bạn chưa cập nhật hình thức nhận tiền lãi đầu tư. Bạn có muốn cập nhật ngay bây giờ không?',
        payFinished:
            '<a>Giao dịch đã hoàn thành, bạn vui lòng chờ vài phút để hệ thống cập nhật!</a>',
        error: 'Không lấy được dữ liệu',
        emptyData1: 'Không có gói đầu tư nào phù hợp.',
        emptyData2: 'Bạn chưa có gói đầu tư nào, cùng đầu tư ngay nào !!!',
        fromDate: 'Từ ngày',
        toDate: 'Đến ngày',
        updateNow: 'Cập nhật ngay',
        unconfirmed: 'Bạn chưa xác thực tài khoản!',
        contentUnconfirmed: 'Xác thực tài khoản để tăng độ an toàn khi đầu tư và sử dụng ứng dụng',
        noAccount: 'Bạn chưa có tài khoản nhận lãi!',
        contentNoAccount: 'Bạn chưa cập nhật hình thức nhận tiền lãi đầu tư. Cập nhật và trải nghiệm đầu tư ngay',
        contentWaitingConfirm: 'Chứng từ của bạn đang được xác minh, bạn có thể tiến hành đầu tư sau khi chứng từ đã được xác thực',
        waitingConfirm: 'Chờ xác minh chứng từ !',
    },
    account: {
        title: 'Tài khoản',
        payMethod: 'Tài khoản nhận tiền',
        linkWallet: 'Liên kết ví điện tử',
        changePwd: 'Đổi mật khẩu',
        loginWithFinger: 'Xác thực nhanh vân tay',
        loginWithFaceId: 'Xác thực nhanh Face ID',
        accountLink: 'Tài khoản liên kết',
        policy: 'Điều kiện và điều khoản',
        shareFriends: 'Mời bạn bè',
        referral: 'Hoa hồng cho nhà đầu tư',
        web: 'TienNgay.vn trên website',
        facebook: 'TienNgay.vn trên Facebook',
        useManual: 'Hướng dẫn sử dụng',
        answer: 'Hỏi đáp',
        hotline: 'Hotline',
        rate: 'Đánh giá cho TienNgay.vn',
        accVerified: 'Tài khoản đã xác thực',
        accuracyNow: 'Xác thực ngay',
        logout: 'Đăng xuất',
        waitVerify: 'Tài khoản đang chờ xác thực',
        logoutNotice: 'Bạn có chắc chắn muốn đăng xuất không?',
        face: 'Face'
    },
    report: {
        title: 'Báo cáo',
        quarterlyOverview: 'Tổng quan theo quý',
        financialChart: 'Biểu đồ tài chính',
        month: 'Tháng',
        investment: 'Vốn đầu tư',
        moneyCollected: 'Tiền thu về',
        overview: 'Tổng quan',
        quarter: 'Quý',
        year: 'Năm',
        monthOfQuarter: 'Chi tiết tháng trong quý',
        contractNumber: 'Số hợp đồng',
        investMoney: 'Số tiền đầu tư',
        originMoneyCollected: 'Số tiền gốc thu về',
        interest: 'Tiền lãi'
    },
    common: {
        search: 'Tìm kiếm',
        agree: 'Đồng ý',
        cancel: 'Hủy',
        continue: 'Tiếp tục',
        vnd: 'VNĐ',
        million: '(Triệu)',
        hotline: '19006907',
        notice: 'Thông báo',
        rate: 'Đánh giá',
        yourRate: 'Đánh giá của bạn',
        comment: 'Nội dung đánh giá',
        descriptionRating: 'Chúng tôi rất hi vọng nhận được đánh giá từ bạn nhằm nâng cao chất lượng phục vụ.',
        descriptionRated: 'Cảm ơn bạn đã đánh giá. Chúng tôi sẽ tiếp nhận ý kiến của bạn để nâng cao chất lượng phục vụ.',
        thanksRating: 'Cám ơn bạn đã đóng góp ý kiến!',
        send: 'Gửi',
        ratedNote: 'Bạn không thể đánh giá lại vì đã đánh giá trước đó!',
        contract: 'Hợp đồng ',
        skip: 'Bỏ qua',
        or: 'Hoặc',
        fileDir: 'file://',
        version: 'Phiên bản 2.4.20230204' 
    },
    introduce: {
        txtIntroduce1: 'Đầu tư an toàn cùng TienNgay.vn',
        txtIntroduce2: 'TienNgay.vn có giấy phép kinh doanh và hoạt động theo quy định của pháp luật và đồng nhất trên toàn hệ thống. Số tiền lãi được trả đúng hạn theo cam kết, giải quyết thắc mắc (nếu có) tận tình, nhanh chóng',
        txtContinue: 'Tiếp tục',
        txtIntroduce3: 'Lãi suất hấp dẫn cùng TienNgay.vn',
        txtIntroduce4: 'Tham gia gửi tiền có kỳ hạn Online tại TienNgay.vn để có thêm thời gian tận hưởng cuộc sống và luôn an tâm rằng tiền của bạn đang sinh lời với lãi suất hấp dẫn.',
        introduce5: 'Rõ ràng - Minh bạch',
        introduce6: 'Tất cả các thao tác của Nhà đầu tư được ghi lại bằng hệ thống của TienNgay.vn, đảm bảo số tiền lãi nhận về rõ ràng, minh bạch.'
    },
    auth: {
        txtPhone: 'Số điện thoại',
        txtPass: 'Mật khẩu',
        txtLogin: 'Đăng nhập',
        txtLoginWith: 'Đăng nhập với',
        txtSignUp: 'Đăng ký',
        txtName: 'Họ và tên',
        txtEmail: 'Email',
        txtRefCode: 'Số điện thoại giới thiệu',
        txtConfirmPass: 'Xác nhận mật khẩu',
        knowChannel: 'Bạn biết chúng tôi qua kênh nào ?',
        txtTitleOtp: 'Xác nhận OTP',
        txtConfirmOtp: 'Nhập mã OTP đã được gửi về điện thoại bạn đã xác nhận',
        conFirm: 'Xác nhận',
        saveAcc: 'Lưu tài khoản',
        forgotPwd: 'Quên mật khẩu',
        txtD: 'Đăng',
        txtK: 'ký',
        titleForgotPass: 'Xác minh số điện thoại',
        txtForgotPass: 'Nhập số điện thoại đã được liên kết với tài khoản của bạn',
        accuracy: 'Xác thực',
        sentOTP: 'Gửi mã',
        txtConfirmNewPass: 'Nhập lại mật khẩu mới',
        txtNewPass: 'Mật khẩu mới',
        titleChangePass: 'Thay đổi mật khẩu',
        txtChange: 'Thay đổi mật khẩu của bạn và đăng nhập lại',
        change: 'Thay đổi',
        succuss: 'Đăng ký thành công',
        notifySuccess: 'Chúc mừng bạn đã đăng ký thành công Đầu tư Tiện ngay. Tiến hành đầu tư ngay và nhận lãi khủng hàng tháng.',
        continue: 'Tiếp tục',
        successChangePass: 'Đổi mật khẩu thành công !',
        done: 'Xong'
    },
    errorMsg: {
        userNameRequired: 'Họ và tên không được để trống',
        userNameLength: 'Họ và tên không được ít hơn 8 ký tự',
        userNameRegex: 'Họ và tên không được chứa ký tự đặc biệt hoặc số',
        emailNull: 'Email không được để trống',
        emailRegex: 'Email không đúng định dạng',
        cardNull: 'Số CMND/CCCD không được để trống',
        cardRegex: 'Số CMND/CCCD phải là số',
        cardCheck: 'Số CMND/CCCD không hợp lệ',
        pwdNull: 'Mật khẩu không được để trống',
        pwdCheck: 'Mật khẩu không được ít hơn 8 ký tự',
        conFirmPwd: 'Xác nhận mật khẩu nhập lại không trùng khớp',
        phoneIsEmpty: 'Số điện thoại không được để trống',
        phoneRegex: 'Số điện thoại không đúng định dạng',
        phoneCount: 'Số điện thoại chỉ được 10 số',
        genderRequired: 'Giới tính không được để trống',
        referralRequired: 'Mã giới thiệu không được để trống',
        channelRequired: 'Nguồn giới thiệu không được để trống',
        addressNull: 'Địa chỉ không được để trống',
        addressRegex: 'Địa chỉ không được chứa kí tự đặc biệt',
        jobNull: 'Nghề nghiệp không được để trống',
        jobRegex: 'Nghề nghiệp không được chứa kí tự đặc biệt',
        birthdayNull: 'Ngày sinh không được để trống',
        birthdayRegex: 'Ngày sinh không đúng định dạng (vd: 05/11/1999)',
        birthdayCompare18: 'Chưa đủ 18 tuổi',
        errStk: 'Số tài khoản hoặc số thẻ ít hơn giới hạn cho phép',
        errStkEmpty: 'Số tài khoản hoặc số thẻ trống',
        errNameEmpty: 'Tên chủ tài khoản ngân hàng trống',
        errBankEmpty: 'Ngân hàng chưa được chọn',
        noInternet: 'Kết nối bị gián đoạn, vui lòng thử lại!',
        sessionExpired: 'Kết nối bị gián đoạn, vui lòng thử lại!',
        errEmptyIdentity: 'Bạn cần điền đầy đủ thông tin trước khi xác thực',
        errSyntaxBank: 'Số thẻ ngân hàng phải từ 8 đến 16 kí tự số',
        errSyntaxATM: 'Số thẻ ATM phải đủ 16 hoặc 19 kí tự số',
        errNotNumberBank: 'Số thẻ ngân hàng phải là kí tự số',
        errNotNumberATM: 'Số thẻ ATM phải là kí tự số',
        uploading: 'Đang tải ảnh lên',
        uploadingError: 'Tải ảnh thất bại',
        emptyRatingPoint: 'Bạn cần phải đánh số sao để đánh giá',
        qrCodeDownloaded: 'Đã tải ảnh Qr-Code thành công',
        copied: 'Đã sao chép',
        topupSuccess: 'TienNgay đã nhận được khoản tiền của bạn.',
        accountNotYetIdentityToInvest: 'Tài khoản của bạn chưa xác thực vui lòng xác thực ngay để đầu tư. Xin cảm ơn'
    },
    quickAuThen: {
        title: 'Mật khẩu và đăng nhập',
        quickButton: 'Sử dụng xác thực nhanh',
        fingerAuThen: 'Bảo mật vân tay',
        faceid: 'Nhận diện khuôn mặt',
        pin: 'Mã Pin',
        changePwd: 'Chỉnh sửa mật khẩu',
        confirm: 'Xác thực của bạn',
        useFaceId: 'Đăng nhập nhanh bằng Face ID',
        useTouchId: 'Đăng nhập nhanh bằng vân tay',
        facIdConFirm:
            'Quý khách có muốn sử dụng Face ID làm phương thức xác thực chính',
        touchIdConfirm:
            'Quý khách có muốn sử dụng vân tay làm phương thức xác thực chính',
        passcodeConfirm:
            'Quý khách có muốn sử dụng mã pin làm phương thức xác thực chính',
        description: 'Đăng nhập bằng vân tay của bạn',
        useFaceID: 'Sử dụng Face ID để đăng nhập vào Đầu tư Tiện Ngay',
        useTouchID: 'Sử dụng Touch ID để đăng nhập vào  Đầu tư Tiện Ngay',

        goToSetting: 'Cài đặt',
        desSetPasscode: 'Vui lòng thêm mã PIN để cài đặt xác thực nhanh',
        desSetTouchId: 'Vui lòng thêm vân tay để xác thực nhanh',
        desSetFaceId: 'Vui lòng thêm Face ID để xác thực nhanh',
        successAddTouchId: 'Đã thêm vân tay vào xác thực nhanh của bạn',
        successAddFaceId: 'Đã thêm Face ID vào xác thực của bạn',
        quickAuthn: 'Xác thực nhanh của bạn'
    },
    setPassCode: {
        titleEnter: 'Xác thực mã PIN',
        titleSetPasscode: 'Sử dụng mã PIN để xác thực nhanh',
        repeat: 'Nhập lại mã PIN',
        errorSet: 'Mã PIN trước và mã PIN sau không trùng khớp',
        errorEnter: 'Mã PIN không đúng',
        footerText: 'Tiếp tục'
    },
    errorBiometryType: {
        NOT_DEFINE: 'Vui lòng thêm ít nhất 1 vân tay vào thiết bị của bạn',
        // ios
        RCTTouchIDNotSupported: 'Không hỗ trợ xác thực vân tay trên thiết bị này',
        RCTTouchIDUnknownError:
            'Đăng nhập thất bại nhiều lần, vui lòng đăng nhập với mật khẩu',
        LAErrorTouchIDNotEnrolled:
            'Vui lòng thêm ít nhất 1 faceId vào thiết bị của bạn',
        LAErrorTouchIDNotAvailable:
            'Không có sẵn xác thực nhanh trên thiết bị của bạn',
        ErrorFaceId: 'Vui lòng thêm ít nhất 1 xác thực faceId vào thiết bị của bạn',
        // android
        NOT_SUPPORTED: 'Không hỗ trợ xác thực vân tay trên thiết bị này',
        NOT_AVAILABLE: 'Không hỗ trợ xác thực vân tay trên thiết bị này',
        NOT_ENROLLED: 'Vui lòng thêm ít nhất 1 vân tay vào thiết bị của bạn',
        FINGERPRINT_ERROR_LOCKOUT_PERMANENT:
            'Xác thực không thành công, thử lại sau',
        LAErrorTouchIDLockout:
            'Đã xảy ra lỗi do đăng nhập quá nhiều lần, vui lòng thử lại sau'
    },
    accountInfo: {
        accountInfo: 'Thông tin cá nhân',
        content: 'Xác thực tài khoản để tăng độ an toàn khi đầu tư và sử dụng ứng dụng',
        noteWaitVerify: 'Tài khoản của bạn đang được xác thực, bạn có thể đầu tư ngay sau khi chứng từ được xác thực',
        accWaitVerify: 'Tài khoản đang được xác thực',
        phoneNumber: 'Số điện thoại',
        gender: 'Giới tính',
        fullName: 'Họ và tên',
        birthday: 'Ngày sinh',
        email: 'Email',
        job: 'Nghề nghiệp',
        address: 'Địa chỉ',
        edit: 'Chỉnh sửa',
        save: 'Lưu lại',
        editAcc: 'Chỉnh sửa thông tin',
        successEdit: 'Chỉnh sửa thông tin thành công',
        chooseAvatarUser: 'Chọn hình đại diện ứng dụng',
        sendingInfo: 'Đang gửi thông tin...'
    },
    accountIdentify: {
        accountIdentify: 'Xác thực tài khoản',
        KYC: 'Số CMND/CCCD',
        imageIdentify: 'Ảnh giấy tờ tùy thân',
        frontKYC: 'Mặt trước CMND',
        behindKYC: 'Mặt sau CMND',
        avatarPhoto: 'Ảnh chân dung chụp:',
        note: '<p><r>Chú ý:</r><s> Hãy xác thực chính xác thông tin của bạn để bắt đầu đầu tư. Sau khi tài khoản bạn được xác thực thành công, bạn không thể thực hiện xác thực lại.</s></p>',
        avatar: 'Chân dung khuôn mặt',
        confirmKYC: 'Xác thực giấy tờ',
        noteTopIdentify: '<p><r>Chú ý:</r><s> Tài khoản của bạn đã được xác thực thành công, bạn không thể thực hiện xác thực lại.</s>',
        waitVerify: 'Chờ xác minh chứng từ',
        waitVerifyContent: 'Chứng từ của bạn đang được xác minh, bạn có thể tiến hành đầu tư sau khi chứng từ đã được xác thực',
        capturePerson: 'Chụp ảnh chân dung',
        noteCapturePerson: 'Chụp cận mặt, rõ, thẳng góc, không bị che, không chụp quá xa. Không chụp chân dung từ ảnh,  màn hình thiết bị điện tử.',
        confirmCapturePerson: 'Sử dụng chân dung của bạn để nhận dạng chứng từ ?',
        captureCard: 'Chụp ảnh chứng từ',
        noteCaptureCard: 'Mặt trước rõ, đủ 4 góc. Không chụp giấy tờ tuỳ thân photo, chụp thông qua màn hình thiết bị điện tử.',
        confirmCaptureCard: 'Sử dụng Chứng từ của bạn để nhận dạng chứng từ ?'
    },
    otp: {
        keyOtp: 'Xác nhận ',
        confirmOtp: 'Hãy nhập và xác nhận mã OTP',
        verificationCode: 'Mã xác thực đã được gửi đến số điện thoại ',
        codeExpiresLater: ' Mã hết hiệu lực sau ',
        resentCode: 'Gửi lại mã',
        popupOtpErrorTitle: 'Thông báo OTP',
        popupOtpErrorDescription: 'OTP không chính xác',
        popupOtpSuccessDescription: 'Đăng ký thành công',
        popupOtpResendCode: 'Mã OTP đã hết hạn. Vui lòng gửi lại',
        sentOtp1: 'Gửi lại mã sau: ',
        sentOtp2: 'Gửi lại mã',
        title: 'Xác thực OTP',
        accuracyPhone: 'Cập nhật thông tin',
        completionOtp: 'Hãy xác nhận mã OTP của chúng tôi đã gửi cho bạn để hoàn thành đầu tư',
        completionPhoneLogin: 'Xin vui lòng nhập các thông tin dưới đây để hoàn thành việc đăng ký tài khoản',
        completionOtpLogin: 'Hãy xác nhận mã OTP chúng tôi đã gửi cho bạn để hoàn thành xác thực.',
        otp1: 'otp1',
        otp2: 'otp2',
        otp3: 'otp3',
        otp4: 'otp4',
        otp5: 'otp5',
        otp6: 'otp6'
    },
    location: {
        PermissionAlert: 'PermissionAlert',
        AccessLocationServices: 'AccessLocationServices',
        OpenSetting: 'OpenSetting',
        Cancel: 'Cancel'
    },
    image: {
        camera: 'Camera',
        library: 'Thư viện ảnh',
        permissionAlert: 'Yêu cầu truy cập',
        accessPhotoMsg: 'Investor cần truy cập vào thư viện ảnh của bạn',
        accessCameraMsg: 'Investor cần truy cập vào camera của bạn',
        accessAddPhotoMsg: 'Investor cần thêm ảnh vào thư viện ảnh của bạn',
        openSetting: 'Mở cài đặt',
        deny: 'Từ chối',
        uploading: 'Đang tải ảnh',
        singleUploading: 'Đang tải ảnh lên',
        selectedThumb: 'Đã chọn hình đại diện',
        selectAsThumb: 'Đặt làm hình đại diện',
        uploadFailed: 'Xảy ra lỗi trong quá trình tải ảnh lên'
    },
    shareFriend: {
        introduce: 'Giới thiệu',
        introduceContent: '<t><c>Giới thiệu thêm nhà đầu tư để có cơ hội nhận những phần quà hấp dẫn tới từ</c> <g>TienNgay.vn</g><c> Đầu tư Tiện ngay</c></t>',
        introduceCode: 'Mã giới thiệu của bạn',
        linkDownload: 'Đường dẫn tải app',
        qrCode: 'QR code tải app'
    },
    referralUsers: {
        title: 'Hoa hồng cho nhà đầu tư',
        des: '<cm><rn>* </rn>Số tiền hoa hồng được hiển thị trong tháng hiện tại là tạm tính và có thể thay đổi theo tổng số tiền đầu tư hàng tháng.\n<rn>*</rn> Chính sách chỉ áp dụng khi người được bạn giới thiệu có đầu tư vào TienNgay. Chính sách có hiệu lực từ ngày <b>%str</b>.</cm>',
        tableDes: 'Chi tiết hoa hồng giới thiệu trong tháng %s',
        colName0: 'Tổng đầu tư',
        colMoney0: 'Tỷ lệ hoa hồng',
        colCommission0: 'Tổng hoa hồng',
        colName: 'Họ và tên',
        colMoney: 'Tổng đầu tư',
        colCommission: 'Hoa hồng',
        noCommission: 'Bạn chưa có hoa hồng từ nhà đầu tư trong tháng %s'
    },
    detailInvest: {
        title: 'Chi tiết khoản đầu tư',
        information: 'Thông tin hợp đồng',
        idContract: 'Mã số hợp đồng',
        interestYear: 'Lãi suất hàng năm',
        interest: 'Lãi suất hàng tháng',
        amountInterest: 'Tổng lãi dự kiến',
        period: 'Kỳ hạn đầu tư',
        day: 'Ngày đầu tư',
        formality: 'Hình thức trả lãi',
        investNow: 'Đầu tư ngay',
        inforInterest: 'Thông tin trả lãi',
        amountMoney: 'Tổng số tiền đầu tư',
        moneyInvest: 'Số tiền đầu tư',
        amountReceived: 'Tổng lãi đã nhận',
        rootRemaining: 'Tổng gốc còn lại',
        rootPaid: 'Tổng gốc đã nhận',
        expectedDate: 'Ngày đáo hạn dự kiến',
        dateDue: 'Ngày đáo hạn',
        reinvest: 'Đầu tư lại',
        interestMonth: 'Lãi hàng tháng',
        money: 'Số tiền cần đầu tư',
        method: 'Phương thức đầu tư',
        vimo: 'Tài khoản Vimo',
        nganLuong: 'Tài khoản Ngân Lượng',
        bank: 'Tài khoản Ngân Hàng',
        linked: 'Đã liên kết',
        paid: 'Đã thanh toán',
        unpaid: 'Chưa thanh toán',
        agreeTermsWith: 'Tôi đã đọc và đồng ý với ',
        rules: 'Điều khoản sử dụng và chính sách ',
        tienngay: 'của TienNgay.vn',
        error: 'Không lấy được dữ liệu, vui lòng thử lại sau',
        notLinked: 'Chưa liên kết',
        infoPayment: 'Thông tin trả lãi'
    },
    changePwd: {
        title: 'Đổi mật khẩu',
        titleUpdatePwd: 'Cập nhật mật khẩu',
        oldPass: 'Mật khẩu cũ',
        newPass: 'Mật khẩu mới',
        confirmPwd: 'Đổi mật khẩu',
        currentNewPass: 'Xác nhận mật khẩu mới',
        placeOldPass: 'Nhập mật khẩu cũ',
        placeNewPass: 'Xác nhận mật khẩu mới',
        button: 'Xác nhận đổi mật khẩu',
        notifyContent: 'Xác nhận đổi mật khẩu',
        notify: 'Thông báo',
        successNotify: 'Xác nhận đổi mật khẩu thành công',
        failOldPwdNotify: 'Mật khẩu cũ không đúng'
    },
    linkSocialAcc: {
        linked: 'Đã liên kết',
        notLinked: 'Chưa liên kết',
        link: 'Liên kết ',
        titleSocial: 'Liên kết tài khoản',
        apple: 'Apple Store',
        fb: 'Facebook',
        google: 'Google',
        notification: 'Thông báo',
        desciption: 'Vui lòng liên kết tài khoản mạng xã hội'
    },
    paymentMethod: {
        methodChoose: 'Chọn phương thức nhận lãi của bạn',
        vimo: 'Tài khoản Vimo',
        bank: 'Tài khoản Ngân hàng',
        cancelLinkVimo: 'Huỷ liên kết ví Vimo',
        changeMethodBank: 'Bạn có muốn chuyển sang liên kết ngân hàng',
        changeMethodVimo: 'Bạn có muốn chuyển sang liên kết Vimo',
        contentCancelLinkVimo: 'Bạn có thật sự muốn huỷ liên kết với ví Vimo. Nếu bạn huỷ liên kết bạn sẽ không thể đầu tư bằng ví Vimo',
        onPressToLink: 'Chạm để liên kết ví',
        onPressToCancelLink: 'Chạm để hủy liên kết ví'
    },
    accountBank: {
        bankChoose: 'Chọn ngân hàng',
        accountNumber: 'Số tài khoản',
        ATMNumber: 'Số thẻ ATM',
        inputAccountNumber: 'Nhập số tài khoản',
        accountProvider: 'Chủ tài khoản',
        accountProviderName: 'Tên chủ tài khoản',
        noteAccountBank: '<p><r>Chú ý:</r> <s>Đây là tài khoản ngân hàng để nhận lãi, bạn cần đảm bảo chính xác thông tin tài khoản ngân hàng bạn cung cấp là chính xác.</s> <g>TienNgay.vn</g><s> sẽ không chịu trách nhiệm khi bạn nhập sai thông tin.</s></p>',
        addAccount: 'Thêm tài khoản',
        updateAccBank: 'Cập nhật tài khoản'
    },
    confirmPhone: {
        confirmPhone: 'Xác nhận số điện thoại',
        noteConfirmPhone: '<p><r>Chú ý:</r> <s>Hãy sử dụng số điện thoại đã đăng ký tài khoản Vimo của bạn để nhận mã OTP</s></p>',
        phone: 'Số điện thoại',
        inputPhone: 'Nhập số điện thoại',
        sendOTP: 'Gửi OTP',
        update: 'Cập nhật thông tin',
        reSendOTP: 'Gửi lại mã OTP',
        verifyOTP: 'Xác nhận OTP',
        noteVerifyOTP: '<p><r>Chú ý:</r> <s> Mã OTP đã được gửi thông qua cuộc gọi tới số điện thoại %phone, nhập mã OTP và xác nhận để liên kết tài khoản</s></p>',
        reSendCode: 'Gửi lại mã sau ',
        sendAgain: 'Gửi lại mã',
        sendAgainTime: 'sau',
        popupOtpResendCode: 'Mã OTP đã hết hạn. Vui lòng gửi lại',
        popupOtpErrorTitle: 'Thông báo OTP',
        popupOtpErrorDescription: 'OTP không chính xác',
        msgCallPhone: 'Mã xác thực đã được gửi đến số điện thoại %s1 thông qua cuộc gọi.'
    },
    msgNotify: {
        successCancelLinkVimo: 'Bạn đã hủy liên kết với Vimo',
        failCancelLinkVimo: 'Hủy liên kết với Vimo thất bại',
        successSendLinkVimo: 'Investor đang gửi mã OTP',
        failSendLinkVimo: 'Số điện thoại này không phải là số liên kết với Vimo',
        successAccountLinkBank: 'Liên kết thành công tài khoản ngân hàng',
        failAccountLinkBank: 'Liên kết thất bại tài khoản ngân hàng',
        failVerifyOTP: 'Mã xác thực OTP không đúng',
        successLinkWithVimo: 'Liên kết thành công với Vimo',
        failPostIdentity: 'Lỗi gửi ảnh',
        successVimoLink: 'Liên kết Vimo thành công',
        failVimoLink: 'Liên kết Vimo thất bại',
        successReOTPVimo: 'Mã OTP đã được gửi lại',
        failReOTPVimo: 'Không thể gửi lại mã OTP',
        successChangeMethod: 'Bạn đã chuyển liên kết thành công',
        failChangeMethod: 'Bạn không thể chuyển liên kết',
        successReceivedCongratulation: 'Chúc mừng bạn đã nhận lãi đầu tư về tài khoản!',
        successInvestedCongratulation: 'Chúc mừng bạn đã đầu tư thành công!'
    },
    loginWithBiometry: {
        hello: '<e>Xin chào,</e>',
        description: '<n><i>Chào mừng bạn quay trở lại với</i><g1> Đầu tư Tiện ngay </g1><i> hãy đăng nhập nào</i></n>',
        loginWithOther: 'Đăng nhập với tài khoản khác'
    },
    biometry: {
        useFingerprint: 'Đăng nhập bằng vân tay của bạn',
        useFingerPrintError: 'Vân tay không khớp, vui lòng thử lại.',
        useFingerPrintManyTimesError:
            'Bạn đã nhập sai quá nhiều lần, vui lòng nhập mã pin.'
    },
    transferScreen: {
        title: 'Chuyển khoản ngân hàng',
        description: 'Để nạp tiền, bạn hãy dùng bất kỳ ngân hàng nào để chuyển khoản đến tài khoản sau: ',
        bank: 'Ngân hàng nhận',
        receiver: 'Tên tài khoản người nhận',
        account: 'Số tài khoản nhận',
        money: 'Số tiền cần chuyển',
        content: 'Nội dung chuyển khoản',
        copy: 'Sao chép',
        alert: 'Nếu nội dung chuyển khoản thiếu hoặc không chính xác. Chúng tôi sẽ không thể nhận ra giao dịch của bạn.',
        or: 'Hoặc thực hiện scan mã Qr code sau:',
        company: 'Cong ty co phan cong nghe tai chinh TienNgay',
        bankName: 'Ngân hàng',
        bankAccount: 'Số tài khoản',
        downloadQrCode: 'Tải ảnh QR-Code',
        pending: 'Giao dịch đang chờ xử lý',
        pendingContent: 'Giao dịch của bạn sẽ được xử lý trong vòng 10 phút kể từ khi chuyển khoản',
        transferred: 'Tôi đã chuyển khoản',
        transferLater: 'Tôi sẽ chuyển khoản sau',
        transferredTitle: 'Cảm ơn bạn đã nạp tiền',
        transferredContent: 'TienNgay sẽ gửi thông báo tới bạn sau vài phút ngay khi tài khoản của bạn nhận được tiền',
        transferLaterTitle: 'Lệnh nạp tiền đang chờ',
        transferLaterContent: 'Lệnh nạp tiền vẫn đang chờ bạn chuyển khoản. Bạn có thể xem lại lệnh nạp tiền của mình trong lịch sử giao dịch và nạp tiền bất cứ lúc nào.',
        goHome: 'Trở về trang chủ'
    },
    update: {
        title: 'Cập nhật phiên bản mới',
        description:
            'Đã có phiên bản cập nhật mới cho ứng dụng. Bạn vui lòng cập nhật để có trải nghiệm tốt hơn.\n\nXin cám ơn.',
        update: 'Cập nhật',
        updating: 'Đang cập nhật phiên bản mới',
        installing: 'Đang cài đặt phiên bản mới'
    },
    maintain: {
        title: 'Thông báo nâng cấp hệ thống',
        description:
            'Hệ thống hiện đang trong quá trình nâng cấp, xin quý nhà đầu tư vui lòng thử lại sau.\nXin cảm ơn!',
        update: 'Đồng ý',
        deleteAccount: 'Xoá tài khoản',
        deleteAccountConfirm: 'Bạn có chắc chắn muốn xoá tài khoản không?\nSau khi xoá tài khoản, bạn không thể đăng nhập vào ứng dụng được nữa. Vui lòng liên hệ 1900 6907 để được hỗ trợ.',
        completionOtpDelete: 'Hãy xác nhận mã OTP chúng tôi đã gửi cho bạn để hoàn thành việc xoá tài khoản.',
        vimo: 'Thông báo dừng cổng thanh toán qua VIMO',
        vimoDes: '<vimo>Từ ngày <b>22/10/2022</b>, TienNgay.vn sẽ dừng các kênh thanh toán, phương thức trả lãi qua ví VIMO. Đề nghị quý nhà đầu tư cập nhật tài khoản ngân hàng để quá trình trả lãi đầu tư không bị gián đoạn.\n\nTienNgay.vn xin lỗi vì bất tiện này.\n</vimo>',
        vimoBtn: 'Cập nhật tài khoản ngân hàng'
    },
    noInternet: {
        offline: 'Kết nối bị gián đoạn',
        desNoInternet: 'Kết nối bị gián đoạn, vui lòng thử lại!'
    },
    notify: {
        readAll: 'Đánh dấu đã đọc toàn bộ',
        readAllNotice: 'Bạn có chắc chắn muốn đánh dấu đã đọc tất cả các thông báo không?',
        turnOnNotify: 'Bật thông báo để không bỏ lỡ bất cứ thông tin nào',
        turnOnNow: 'Bật ngay',
    }
};
export default Languages;
